clas12::ZVertexFilter:

  # the name of the particle bank, only used for users of `hipo::banklist`;
  # e.g., set it to 'MC::Particle' if you prefer
  particle_bank: 'REC::Particle'

  # scattered electron cuts
  electron:

    # default cuts
    - default:
      vz: [ -20.0, 20.0 ]

    ### RUN GROUP A ###########

    # RG-A spring2018 inbending, 1st period
    - runs: [ 3031, 3087 ]
      vz: [ -6.061, 1.819 ]

    # RG-A spring2018 outbending, 1st period
    - runs: [ 3103, 3293 ]
      vz: [ -7.272, 0.909 ]

    # RG-A spring2018 inbending, 2nd period
    - runs: [ 3306, 3817 ]
      vz: [ -6.061, 1.819 ]

    # RG-A spring2018 outbending, 2nd period
    - runs: [ 3820, 3987 ]
      vz: [ -7.272, 0.909 ]

    # RG-A spring2018 inbending, 3rd period
    - runs: [ 4003, 4325 ]
      vz: [ -6.061, 1.819 ]

    # RG-A fall2018 inbending
    - runs: [ 4763, 5419 ]
      vz: [ -6.364, 1.515 ]

    # RG-A fall2018 outbending
    - runs: [ 5423, 5666 ]
      vz: [ -7.879, 0.303 ]

    # RG-A spring2019 inbending
    - runs: [ 6616, 6783 ]
      vz: [ -6.364, 1.515 ]

    ### RUN GROUP B ###########
    # FIXME: these are not yet the official, common RG-B vertex cuts; for now,
    # they are just the cuts that C. Dilks is using for SIDIS analysis.

    # RG-B spring2019 inbending # FIXME: not official (see FIXME above)
    - runs: [ 6156, 6603 ]
      vz: [ -8.0, 3.0 ]

    # RG-B fall2019 outbending # FIXME: not official (see FIXME above)
    - runs: [ 11093, 11283 ]
      vz: [ -10.0, 2.5 ]

    # RG-B spring2020 inbending # FIXME: not official (see FIXME above)
    - runs: [ 11323, 11571 ]
      vz: [ -8.0, 3.0 ]
