clas12::SectorFinder:
  # if not 'default', use this bank for sector finding of charged particles
  bank_charged: default
  # if not 'default', use this bank for sector finding of neutral particles
  bank_neutral: default
