version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/bind/python" # requirements.txt for pyiguana
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/doc/mkdocs" # requirements.txt for mkdocs
    schedule:
      interval: "weekly"
